services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    env_file:
      - ./.env   # Load environment variables from this file
    volumes:
      - ./settings/data:/app/settings/data  # Persist SQLite DB data
    restart: unless-stopped
